-- Real LA area/neighborhood taxonomy, replacing the placeholder
-- Eastside/Westside fixture data. Neighborhoods are the LA Times'
-- Mapping L.A. project boundaries (114 official City of LA
-- neighborhoods, verified against the live dataset at
-- data-lahub.opendata.arcgis.com) extended with the surrounding LA
-- County neighborhoods under the same project's 16 regions, since real
-- comedy venues sit outside city limits too (e.g. the existing seed
-- venue "Westside Comedy Theater" is in Santa Monica).
--
-- Idempotent (on conflict do nothing) so this file can run safely
-- against local dev (via config.toml's db.seed.sql_paths) and, once,
-- against production via psql or the Studio SQL editor.

insert into areas (name) values
  ('Angeles Forest'),
  ('Antelope Valley'),
  ('Central L.A.'),
  ('Eastside'),
  ('Harbor'),
  ('Northeast L.A.'),
  ('Northwest County'),
  ('Pomona Valley'),
  ('San Fernando Valley'),
  ('San Gabriel Valley'),
  ('Santa Monica Mountains'),
  ('South Bay'),
  ('South L.A.'),
  ('Southeast'),
  ('Verdugos'),
  ('Westside')
on conflict (name) do nothing;

insert into neighborhoods (name)
select v.name from (values
  ('Acton'),
  ('Adams-Normandie'),
  ('Agoura Hills'),
  ('Agua Dulce'),
  ('Alhambra'),
  ('Alondra Park'),
  ('Altadena'),
  ('Angeles National Forest'),
  ('Arcadia'),
  ('Arleta'),
  ('Arlington Heights'),
  ('Artesia'),
  ('Atwater Village'),
  ('Avocado Heights'),
  ('Azusa'),
  ('Baldwin Hills/Crenshaw'),
  ('Baldwin Park'),
  ('Bel-Air'),
  ('Bell'),
  ('Bell Gardens'),
  ('Bellflower'),
  ('Beverly Crest'),
  ('Beverly Grove'),
  ('Beverly Hills'),
  ('Beverlywood'),
  ('Boyle Heights'),
  ('Bradbury'),
  ('Brentwood'),
  ('Broadway-Manchester'),
  ('Burbank'),
  ('Calabasas'),
  ('Canoga Park'),
  ('Carson'),
  ('Carthay'),
  ('Castaic'),
  ('Castaic Junction'),
  ('Central-Alameda'),
  ('Century City'),
  ('Cerritos'),
  ('Chatsworth'),
  ('Chatsworth Reservoir'),
  ('Chesterfield Square'),
  ('Cheviot Hills'),
  ('Chinatown'),
  ('City of Industry'),
  ('Claremont'),
  ('Commerce'),
  ('Covina'),
  ('Cudahy'),
  ('Culver City'),
  ('Cypress Park'),
  ('Del Aire'),
  ('Del Rey'),
  ('Desert View Highlands'),
  ('Diamond Bar'),
  ('Downey'),
  ('Downtown'),
  ('Duarte'),
  ('Eagle Rock'),
  ('East Hollywood'),
  ('East Pasadena'),
  ('Echo Park'),
  ('El Monte'),
  ('El Segundo'),
  ('El Sereno'),
  ('Elysian Park'),
  ('Elysian Valley'),
  ('Encino'),
  ('Exposition Park'),
  ('Fairfax'),
  ('Florence'),
  ('Florence-Firestone'),
  ('Gardena'),
  ('Glassell Park'),
  ('Glendale'),
  ('Glendora'),
  ('Gorman'),
  ('Gramercy Park'),
  ('Granada Hills'),
  ('Green Meadows'),
  ('Green Valley'),
  ('Griffith Park'),
  ('Hacienda Heights'),
  ('Hancock Park'),
  ('Hansen Dam'),
  ('Harbor City'),
  ('Harbor Gateway'),
  ('Harvard Heights'),
  ('Harvard Park'),
  ('Hasley Canyon'),
  ('Hawaiian Gardens'),
  ('Hawthorne'),
  ('Hermosa Beach'),
  ('Hidden Hills'),
  ('Highland Park'),
  ('Historic South-Central'),
  ('Hollywood'),
  ('Hollywood Hills'),
  ('Hollywood Hills West'),
  ('Huntington Park'),
  ('Hyde Park'),
  ('Inglewood'),
  ('Irwindale'),
  ('Jefferson Park'),
  ('Koreatown'),
  ('La Cañada Flintridge'),
  ('La Crescenta-Montrose'),
  ('La Mirada'),
  ('La Puente'),
  ('La Verne'),
  ('Lake Balboa'),
  ('Lake Hughes'),
  ('Lake Los Angeles'),
  ('Lake View Terrace'),
  ('Lakewood'),
  ('Lancaster'),
  ('Larchmont'),
  ('Lawndale'),
  ('Leimert Park'),
  ('Leona Valley'),
  ('Lincoln Heights'),
  ('Little Tokyo'),
  ('Littlerock'),
  ('Llano'),
  ('Lomita'),
  ('Los Feliz'),
  ('Lynwood'),
  ('Malibu'),
  ('Manchester Square'),
  ('Manhattan Beach'),
  ('Mar Vista'),
  ('Marina del Rey'),
  ('Mayford'),
  ('Maywood'),
  ('Mid-City'),
  ('Mid-Wilshire'),
  ('Mission Hills'),
  ('Monrovia'),
  ('Montecito Heights'),
  ('Monterey Park'),
  ('Mount Baldy'),
  ('Mount Washington'),
  ('North Hills'),
  ('North Hollywood'),
  ('Northridge'),
  ('Norwalk'),
  ('Pacific Palisades'),
  ('Pacoima'),
  ('Palmdale'),
  ('Palms'),
  ('Palos Verdes Estates'),
  ('Panorama City'),
  ('Paramount'),
  ('Pasadena'),
  ('Pearblossom'),
  ('Pico Rivera'),
  ('Pico-Robertson'),
  ('Pico-Union'),
  ('Playa Vista'),
  ('Playa del Rey'),
  ('Pomona'),
  ('Porter Ranch'),
  ('Quartz Hill'),
  ('Rancho Palos Verdes'),
  ('Rancho Park'),
  ('Redondo Beach'),
  ('Reseda'),
  ('Rolling Hills'),
  ('Rolling Hills Estates'),
  ('Rosemead'),
  ('Rowland Heights'),
  ('San Dimas'),
  ('San Fernando'),
  ('San Gabriel'),
  ('San Marino'),
  ('San Pedro'),
  ('Santa Clarita'),
  ('Santa Monica'),
  ('Sawtelle'),
  ('Sepulveda Basin'),
  ('Shadow Hills'),
  ('Sherman Oaks'),
  ('Sierra Madre'),
  ('Signal Hill'),
  ('Silver Lake'),
  ('South El Monte'),
  ('South Gate'),
  ('South Park'),
  ('South Pasadena'),
  ('South San Gabriel'),
  ('Stevenson Ranch'),
  ('Studio City'),
  ('Sun Valley'),
  ('Sun Village'),
  ('Sunland'),
  ('Sylmar'),
  ('Tarzana'),
  ('Temple City'),
  ('Toluca Lake'),
  ('Topanga'),
  ('Torrance'),
  ('Tujunga'),
  ('Universal City'),
  ('University Park'),
  ('Val Verde'),
  ('Valinda'),
  ('Valley Glen'),
  ('Valley Village'),
  ('Valyermo'),
  ('Van Nuys'),
  ('Venice'),
  ('Vermont Knolls'),
  ('Vermont Square'),
  ('Vermont Vista'),
  ('Vermont-Slauson'),
  ('Vincent'),
  ('Watts'),
  ('West Adams'),
  ('West Carson'),
  ('West Covina'),
  ('West Hills'),
  ('West Hollywood'),
  ('West Los Angeles'),
  ('West Puente Valley'),
  ('Westchester'),
  ('Westlake'),
  ('Westlake Village'),
  ('Westwood'),
  ('Whittier'),
  ('Willowbrook'),
  ('Wilmington'),
  ('Windsor Square'),
  ('Winnetka'),
  ('Woodland Hills')
) as v(name)
on conflict (name) do nothing;

insert into neighborhood_areas (neighborhood_id, area_id)
select n.id, a.id
from (values
  ('Angeles National Forest', 'Angeles Forest'),
  ('Mount Baldy', 'Angeles Forest'),
  ('Acton', 'Antelope Valley'),
  ('Agua Dulce', 'Antelope Valley'),
  ('Desert View Highlands', 'Antelope Valley'),
  ('Green Valley', 'Antelope Valley'),
  ('Lake Los Angeles', 'Antelope Valley'),
  ('Lancaster', 'Antelope Valley'),
  ('Leona Valley', 'Antelope Valley'),
  ('Littlerock', 'Antelope Valley'),
  ('Llano', 'Antelope Valley'),
  ('Palmdale', 'Antelope Valley'),
  ('Pearblossom', 'Antelope Valley'),
  ('Quartz Hill', 'Antelope Valley'),
  ('Sun Village', 'Antelope Valley'),
  ('Valyermo', 'Antelope Valley'),
  ('Arlington Heights', 'Central L.A.'),
  ('Beverly Grove', 'Central L.A.'),
  ('Carthay', 'Central L.A.'),
  ('Chinatown', 'Central L.A.'),
  ('Downtown', 'Central L.A.'),
  ('East Hollywood', 'Central L.A.'),
  ('Echo Park', 'Central L.A.'),
  ('Elysian Park', 'Central L.A.'),
  ('Fairfax', 'Central L.A.'),
  ('Griffith Park', 'Central L.A.'),
  ('Hancock Park', 'Central L.A.'),
  ('Harvard Heights', 'Central L.A.'),
  ('Hollywood', 'Central L.A.'),
  ('Koreatown', 'Central L.A.'),
  ('Larchmont', 'Central L.A.'),
  ('Little Tokyo', 'Central L.A.'),
  ('Los Feliz', 'Central L.A.'),
  ('Mid-City', 'Central L.A.'),
  ('Mid-Wilshire', 'Central L.A.'),
  ('Pico-Union', 'Central L.A.'),
  ('Silver Lake', 'Central L.A.'),
  ('Westlake', 'Central L.A.'),
  ('Windsor Square', 'Central L.A.'),
  ('Boyle Heights', 'Eastside'),
  ('El Sereno', 'Eastside'),
  ('Lincoln Heights', 'Eastside'),
  ('Los Feliz', 'Eastside'),
  ('Silver Lake', 'Eastside'),
  ('Harbor City', 'Harbor'),
  ('Harbor Gateway', 'Harbor'),
  ('San Pedro', 'Harbor'),
  ('Wilmington', 'Harbor'),
  ('Atwater Village', 'Northeast L.A.'),
  ('Cypress Park', 'Northeast L.A.'),
  ('Eagle Rock', 'Northeast L.A.'),
  ('Elysian Valley', 'Northeast L.A.'),
  ('Glassell Park', 'Northeast L.A.'),
  ('Highland Park', 'Northeast L.A.'),
  ('Montecito Heights', 'Northeast L.A.'),
  ('Mount Washington', 'Northeast L.A.'),
  ('Castaic', 'Northwest County'),
  ('Castaic Junction', 'Northwest County'),
  ('Gorman', 'Northwest County'),
  ('Hasley Canyon', 'Northwest County'),
  ('Lake Hughes', 'Northwest County'),
  ('Santa Clarita', 'Northwest County'),
  ('Stevenson Ranch', 'Northwest County'),
  ('Val Verde', 'Northwest County'),
  ('Claremont', 'Pomona Valley'),
  ('Diamond Bar', 'Pomona Valley'),
  ('La Verne', 'Pomona Valley'),
  ('Pomona', 'Pomona Valley'),
  ('San Dimas', 'Pomona Valley'),
  ('Arleta', 'San Fernando Valley'),
  ('Burbank', 'San Fernando Valley'),
  ('Calabasas', 'San Fernando Valley'),
  ('Canoga Park', 'San Fernando Valley'),
  ('Chatsworth', 'San Fernando Valley'),
  ('Chatsworth Reservoir', 'San Fernando Valley'),
  ('Encino', 'San Fernando Valley'),
  ('Glendale', 'San Fernando Valley'),
  ('Granada Hills', 'San Fernando Valley'),
  ('Hidden Hills', 'San Fernando Valley'),
  ('Lake Balboa', 'San Fernando Valley'),
  ('Mission Hills', 'San Fernando Valley'),
  ('North Hills', 'San Fernando Valley'),
  ('North Hollywood', 'San Fernando Valley'),
  ('Northridge', 'San Fernando Valley'),
  ('Pacoima', 'San Fernando Valley'),
  ('Panorama City', 'San Fernando Valley'),
  ('Porter Ranch', 'San Fernando Valley'),
  ('Reseda', 'San Fernando Valley'),
  ('San Fernando', 'San Fernando Valley'),
  ('Sepulveda Basin', 'San Fernando Valley'),
  ('Sherman Oaks', 'San Fernando Valley'),
  ('Studio City', 'San Fernando Valley'),
  ('Sun Valley', 'San Fernando Valley'),
  ('Sylmar', 'San Fernando Valley'),
  ('Tarzana', 'San Fernando Valley'),
  ('Toluca Lake', 'San Fernando Valley'),
  ('Universal City', 'San Fernando Valley'),
  ('Valley Glen', 'San Fernando Valley'),
  ('Valley Village', 'San Fernando Valley'),
  ('Van Nuys', 'San Fernando Valley'),
  ('West Hills', 'San Fernando Valley'),
  ('Winnetka', 'San Fernando Valley'),
  ('Woodland Hills', 'San Fernando Valley'),
  ('Alhambra', 'San Gabriel Valley'),
  ('Altadena', 'San Gabriel Valley'),
  ('Arcadia', 'San Gabriel Valley'),
  ('Avocado Heights', 'San Gabriel Valley'),
  ('Azusa', 'San Gabriel Valley'),
  ('Baldwin Park', 'San Gabriel Valley'),
  ('Bradbury', 'San Gabriel Valley'),
  ('City of Industry', 'San Gabriel Valley'),
  ('Covina', 'San Gabriel Valley'),
  ('Duarte', 'San Gabriel Valley'),
  ('East Pasadena', 'San Gabriel Valley'),
  ('El Monte', 'San Gabriel Valley'),
  ('Glendora', 'San Gabriel Valley'),
  ('Hacienda Heights', 'San Gabriel Valley'),
  ('Irwindale', 'San Gabriel Valley'),
  ('La Puente', 'San Gabriel Valley'),
  ('Mayford', 'San Gabriel Valley'),
  ('Monrovia', 'San Gabriel Valley'),
  ('Monterey Park', 'San Gabriel Valley'),
  ('Pasadena', 'San Gabriel Valley'),
  ('Rosemead', 'San Gabriel Valley'),
  ('Rowland Heights', 'San Gabriel Valley'),
  ('San Gabriel', 'San Gabriel Valley'),
  ('San Marino', 'San Gabriel Valley'),
  ('Sierra Madre', 'San Gabriel Valley'),
  ('South El Monte', 'San Gabriel Valley'),
  ('South Pasadena', 'San Gabriel Valley'),
  ('South San Gabriel', 'San Gabriel Valley'),
  ('Temple City', 'San Gabriel Valley'),
  ('Valinda', 'San Gabriel Valley'),
  ('Vincent', 'San Gabriel Valley'),
  ('West Covina', 'San Gabriel Valley'),
  ('West Puente Valley', 'San Gabriel Valley'),
  ('Agoura Hills', 'Santa Monica Mountains'),
  ('Bel-Air', 'Santa Monica Mountains'),
  ('Beverly Crest', 'Santa Monica Mountains'),
  ('Brentwood', 'Santa Monica Mountains'),
  ('Hidden Hills', 'Santa Monica Mountains'),
  ('Hollywood Hills', 'Santa Monica Mountains'),
  ('Hollywood Hills West', 'Santa Monica Mountains'),
  ('Malibu', 'Santa Monica Mountains'),
  ('Pacific Palisades', 'Santa Monica Mountains'),
  ('Topanga', 'Santa Monica Mountains'),
  ('Westlake Village', 'Santa Monica Mountains'),
  ('Alondra Park', 'South Bay'),
  ('Carson', 'South Bay'),
  ('Del Aire', 'South Bay'),
  ('El Segundo', 'South Bay'),
  ('Gardena', 'South Bay'),
  ('Hawthorne', 'South Bay'),
  ('Hermosa Beach', 'South Bay'),
  ('Lawndale', 'South Bay'),
  ('Lomita', 'South Bay'),
  ('Manhattan Beach', 'South Bay'),
  ('Palos Verdes Estates', 'South Bay'),
  ('Rancho Palos Verdes', 'South Bay'),
  ('Redondo Beach', 'South Bay'),
  ('Rolling Hills', 'South Bay'),
  ('Rolling Hills Estates', 'South Bay'),
  ('Torrance', 'South Bay'),
  ('West Carson', 'South Bay'),
  ('Adams-Normandie', 'South L.A.'),
  ('Baldwin Hills/Crenshaw', 'South L.A.'),
  ('Broadway-Manchester', 'South L.A.'),
  ('Central-Alameda', 'South L.A.'),
  ('Chesterfield Square', 'South L.A.'),
  ('Exposition Park', 'South L.A.'),
  ('Florence', 'South L.A.'),
  ('Florence-Firestone', 'South L.A.'),
  ('Gramercy Park', 'South L.A.'),
  ('Green Meadows', 'South L.A.'),
  ('Harvard Park', 'South L.A.'),
  ('Historic South-Central', 'South L.A.'),
  ('Hyde Park', 'South L.A.'),
  ('Inglewood', 'South L.A.'),
  ('Jefferson Park', 'South L.A.'),
  ('Leimert Park', 'South L.A.'),
  ('Lynwood', 'South L.A.'),
  ('Manchester Square', 'South L.A.'),
  ('Pico-Robertson', 'South L.A.'),
  ('South Park', 'South L.A.'),
  ('University Park', 'South L.A.'),
  ('Vermont Knolls', 'South L.A.'),
  ('Vermont Square', 'South L.A.'),
  ('Vermont Vista', 'South L.A.'),
  ('Vermont-Slauson', 'South L.A.'),
  ('Watts', 'South L.A.'),
  ('West Adams', 'South L.A.'),
  ('Willowbrook', 'South L.A.'),
  ('Artesia', 'Southeast'),
  ('Bell', 'Southeast'),
  ('Bell Gardens', 'Southeast'),
  ('Bellflower', 'Southeast'),
  ('Cerritos', 'Southeast'),
  ('Commerce', 'Southeast'),
  ('Cudahy', 'Southeast'),
  ('Downey', 'Southeast'),
  ('Hawaiian Gardens', 'Southeast'),
  ('Huntington Park', 'Southeast'),
  ('La Mirada', 'Southeast'),
  ('Lakewood', 'Southeast'),
  ('Maywood', 'Southeast'),
  ('Norwalk', 'Southeast'),
  ('Paramount', 'Southeast'),
  ('Pico Rivera', 'Southeast'),
  ('Signal Hill', 'Southeast'),
  ('South Gate', 'Southeast'),
  ('Whittier', 'Southeast'),
  ('Hansen Dam', 'Verdugos'),
  ('La Cañada Flintridge', 'Verdugos'),
  ('La Crescenta-Montrose', 'Verdugos'),
  ('Lake View Terrace', 'Verdugos'),
  ('Shadow Hills', 'Verdugos'),
  ('Sunland', 'Verdugos'),
  ('Tujunga', 'Verdugos'),
  ('Beverly Hills', 'Westside'),
  ('Beverlywood', 'Westside'),
  ('Century City', 'Westside'),
  ('Cheviot Hills', 'Westside'),
  ('Culver City', 'Westside'),
  ('Del Rey', 'Westside'),
  ('Mar Vista', 'Westside'),
  ('Marina del Rey', 'Westside'),
  ('Palms', 'Westside'),
  ('Playa Vista', 'Westside'),
  ('Playa del Rey', 'Westside'),
  ('Rancho Park', 'Westside'),
  ('Santa Monica', 'Westside'),
  ('Sawtelle', 'Westside'),
  ('Venice', 'Westside'),
  ('West Hollywood', 'Westside'),
  ('West Los Angeles', 'Westside'),
  ('Westchester', 'Westside'),
  ('Westwood', 'Westside')
) as v(neighborhood_name, area_name)
join neighborhoods n on n.name = v.neighborhood_name
join areas a on a.name = v.area_name
on conflict (neighborhood_id, area_id) do nothing;
